version: '3'

services:
  django:
    build:
      context: django
      dockerfile: ./Dockerfile
    environment:
      - DEBUG_MODE=True  
    #command: ["poetry", "run", "gunicorn", "--bind", ":8000", "--workers", "1", "Project_Django_Boilerplate_GAP.wsgi"]
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./django/:/Django_app

  keycloak:
    image: jboss/keycloak:16.1.1
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    expose:
      - 8080
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/default_realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/default_realm.json:/opt/jboss/keycloak/default_realm.json